language: c

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  # password is encrypted below
  - echo "Sys.setenv('plotly_username' = 'RTestBot3000')" > ~/.Rprofile

install:
  - ./travis-tool.sh install_deps

before_script:
  - git config --global user.name "cpsievert"
  - git config --global user.email "cpsievert1@gmail.com"
  - git clone https://github.com/cpsievert/plotly-test-table.git ../plotly-test-table

script:
  - Rscript -e "devtools::install(); source('tests/testthat.R', chdir = TRUE)"

after_success:
  - cd ../plotly-test-table
  - ls -R
  - Rscript ../plotly/inst/build-push-comment.R

env:
  matrix:
    - TEST_SUITE=cookbook_axes
    - TEST_SUITE=cookbook_lines
    - TEST_SUITE=cookbook_scatterplots
    - TEST_SUITE=ggplot_abline
    - TEST_SUITE=cookbook_axes
    - TEST_SUITE=cookbook_lines
    - TEST_SUITE=cookbook_scatterplots
    - TEST_SUITE=ggplot_abline
    - TEST_SUITE=ggplot_area
    - TEST_SUITE=ggplot_bar
    - TEST_SUITE=ggplot_boxplot
    - TEST_SUITE=ggplot_build2
    - TEST_SUITE=ggplot_categorical
    - TEST_SUITE=ggplot_contour
    - TEST_SUITE=ggplot_date
    - TEST_SUITE=ggplot_density
    - TEST_SUITE=ggplot_density2d
    - TEST_SUITE=ggplot_errorbar_horizontal
    - TEST_SUITE=ggplot_errorbar
    - TEST_SUITE=ggplot_facets
    - TEST_SUITE=ggplot_heatmap
    - TEST_SUITE=ggplot_histogram
    - TEST_SUITE=ggplot_hline
    - TEST_SUITE=ggplot_labels
    - TEST_SUITE=ggplot_legend
    - TEST_SUITE=ggplot_linetype
    - TEST_SUITE=ggplot_names
    - TEST_SUITE=ggplot_path
    - TEST_SUITE=ggplot_polygons
    - TEST_SUITE=ggplot_rect
    - TEST_SUITE=ggplot_ribbon
    - TEST_SUITE=ggplot_segment
    - TEST_SUITE=ggplot_size
    - TEST_SUITE=ggplot_smooth
    - TEST_SUITE=ggplot_stack
    - TEST_SUITE=ggplot_step
    - TEST_SUITE=ggplot_text
    - TEST_SUITE=ggplot_theme
    - TEST_SUITE=ggplot_ticks
    - TEST_SUITE=ggplot_vline
    - TEST_SUITE=ggplot_ylim
    - TEST_SUITE=mean_error_bars
    - TEST_SUITE=plotly_filename
    - TEST_SUITE=plotly_getfigure
    - TEST_SUITE=plotly_knitr
    - TEST_SUITE=plotly_subplot
    - TEST_SUITE=plotly
    - TEST_SUITE=rotated_ticks
  global:
    # plotly_api_key (for posting to plot.ly)
    - secure: "UAETDsmeXkXm9eUpZa3JTm8/cv+jyLmArXE0TQD0yQNICFNPkGeNergoQmkesRqG+ifLu6V1lPXu1XlqQPdXY60clUHThDN+AjsBmcv9F170k6RtBSV8pIKL9fsW8t0v/maEet86qOSf3cNa5+gK8GjBH1pmLrN2rF9r7RhwUdg="
    # GITHUB_PAT (for pushing to plotly-test-table)
    - secure: "LHJONgWOo+98vNeFLI7LSJU3RtbMVszlI79GB8CcXmc2mlgM/UtZ5b6RnkNlhmg3Gj1/uObfm/rIybVTwuS1yNpeKv73+gsZOYhobVXiUGVxdRFG/mg5mbqwyWkkuofjPGFlMZCEMgHim37eZzgjSibwVH1LClRDsCoFMCgvgV0="
    # plotlyjs_full (link to the full offline bundle)
    - secure: "ivxfqGwbzpBpVJe+jVcOBktcmLrT38W/ZapAk/FNDu+yaBhag1eCYErAPPx6Snc4GzwatMt22v4SxAqXQF4SAhTRtmrWVaWnbhzuNqpTkiS6IKEd6EqaoyUZvUTgXh1ruyik00zl3ET9898O3vFfqafodljE0lCLVICHq6ANo68="
    # plotlyjs_no_jq (link to the offline bundle w/o jQuery)
    - secure: "i5cYEs2lCFSYgrSTHMmzzs8hRwAwiz89GpgM16fqUDQz8T1QMWofNugQInS7fIfKL36FoTz8BaiLs2D98/2kDkkZ0LTHnfrdrY9PO+7D+CmL8QeLLp4atBT0i682nwy8RzEqlvB8yAVQo/i0Eh8tmT97pppddsxttZKoUidfOeA="
